name: Python Unittest and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r ./tests/requirements-test.txt
        pip install coverage coverage-badge

    - name: Run Unittests and Generate Coverage Report
      env:
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_DKIM_SELECTOR: ${{ secrets.MAIL_DKIM_SELECTOR }}
        MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
        MAIL_SENDER_NAME: ${{ secrets.MAIL_SENDER_NAME }}
        MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      run: |
        coverage run -m unittest discover
        coverage xml
        coverage-badge -o ./tests/assets/coverage.svg

    # Commit and Push Coverage Badge
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update coverage badge
        file_pattern: tests/assets/coverage.svg
        commit_options: '--no-verify'
        branch: main
