name: Python Unittest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r ./tests/requirements-test.txt
        pip install coverage coverage-badge
    - name: Run Unittests and Generate Coverage Report
      env:
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_DKIM_SELECTOR: ${{ secrets.MAIL_DKIM_SELECTOR }}
        MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
        MAIL_SENDER_NAME: ${{ secrets.MAIL_SENDER_NAME }}
        MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      run: |
        coverage run -m unittest discover
        coverage xml
        coverage-badge -o ./tests/assets/coverage.svg
    # After generating the coverage badge
    - name: Commit and Push Coverage Badge
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update coverage badge
        file_pattern: tests/assets/coverage.svg
        commit_options: '--no-verify'
        repository: .
        branch: ${{ github.ref }}
        commit_user_name: Lewis Morris
        commit_user_email: lewis@arched.dev
        commit_author: Lewis Morris <lewis@arched.dev>
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
