name: Python Unittest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Unittests and Generate Coverage Report
      env:
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_DKIM_SELECTOR: ${{ secrets.MAIL_DKIM_SELECTOR }}
        MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
        MAIL_SENDER_NAME: ${{ secrets.MAIL_SENDER_NAME }}
        MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      run: |
        cd tests
        coverage run -m unittest discover
        coverage xml
        mkdir -p assets  # Ensure the assets directory exists
        coverage-badge -o assets/coverage.svg
    - name: Commit and Push Coverage Badge
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add tests/assets/coverage.svg
        git commit -m "Update coverage badge"
        git push
